appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: deTHWHpzGevWgsWKiWuKi4HHsknxf4d+vB6bPnM1r8BF4slRMJShIB2iBY67xOp9aUv2MmnX7lEJFR2e+23Wob9BBDFdmaZjIaRWWI5D/rucIGzvvMkWnyoSIIj15zau/Borlzipf7u5KBi+H+JQlBzOV7W7GUi4vVcqq2VKS8YvxPj19yt/sMWaUcH43+gWInpgkyq0aJRfjgBeyydP2DnvsjzAZruHwPpxC9l3csFOUBdL5NQx92dgEeJt/YC9ysENeKMilFEQImTChLgUhsvpjnM04otvKKfFRovws9reFD5DWLndUwNsftoKQ//B1WnRi8gb7DMaKjhamAGFsptPTqcZFiCyk9SfchLHboknl8UOSoJ0tilEn3/JUlEkzgF4Sw9hST1NepWccby1U8FUKTnz3ixzyfFAfp+xnbdBoHOFcKymY90/OhadZrmc1SAYHu5IuiX13zyZDcfOoUDqOO2q6EiQGqxg8jch8H5oK7iWy/j1yAK3J85FxgUgLVZLGXGY16AttUWRpCtjRikATvBcBVZnuOuZIX8JXiaqmDBP4yF+lVZMiBZVDkJomSM51OS0BaNzFjNRe8h70aorm+8beG0XMD+8KOGH3w+dLQnpGILTb8w//QPgGYBmeGLPDOcxaDJWG20TBtC877m6EQZ/i3oDHVvF7ApWGGQ=
conda_forge_output_validation: true
