travis:
  secure:
    BINSTAR_TOKEN: pAOOUWhlljqW0bBw9iBQuka9ekn0tPzAX8Tkv8/XjWqfUIRk6JXtNfOrumhiJNjIOPzxS1y7vZH5g12WVn6XXcwCyJzxVE20IizLmSeOFt310v2cPlXX2rh7LJgnZYwqJZupNp+W9eTLqk0Vg1T5nr25wt2xmmg9y6LyGGZjt9oZVMa4n5eywPOJ4h1eNxbLSiS+e/VETOjW+d705tCIndMiEgfS0KrcIH02sE88rpy4cZT0qpiiAWb6V1ZGZgpt78U8ZiJCUNhJO8OdBfrHoDZK7vNqC5E2okQsqfzrJWa1MB+wHUeWz8s/q9PBBLoiDxdDKG8MecvyFSQNMKpxlCzWQmHoPytCqYbqJi4kwzYOGCg1GttRWCBmc8Xln9G+Ld01mXPWQhCghgA1+B96JlFcKUl0WOcCIdBXSNumqytFv6Pt8hz6ldwU0JMjxfCGj6RhLOhN7r2qK1xWszIdLJrJVsRdxTYQK+vAaw3ur+9BYQc2F2s9hbLIfcXdYmwhVEyrD91BOljPh/CKPOGe2TLn6J8o8q+l0FONMuBiCZeSbbFCCIdeOQ5kroM8pwVU4TBP9wDFA+nYaVQCBRhGgLMWitC2V6LByoEIF8xHNGU36PzUozX4TwXT0tQk+VDCf7GKmNI2OOWbjkyeWiFkKMR6jc3rr50K2E9M45nmtO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
