travis:
  secure:
    BINSTAR_TOKEN: BAHYqOo28WtnWX6280x7Aai0cRC6ctc7PN7O1I3rTgXMnMLpPTC6ntXRBfohYjUSOxmgz5eYm0TBlVQ2JKVjMa4h3nCJ7cKgyFYLKv1fQRI52O79kDIaLgTa2axca7RbikgaYyvzIZW4RIuuKge0uOZRpiSqZ23R60GZzY7qqpBgWKvf2VE+OQnM+qFts094/e8YxAq8VR4/ibSmgScWs1sVZFehwolJUNhqZ8/gMqhzW9bTe4OWq1Zv0/ds94Ldom6ktIzrzpDtjej9qKN8wh7XJtup8seJUiG5mOOVL5QPrrxNWpJwzXtQ2r2CQpkYufdQeGdRLSMn3S4R5AFydYo8/7fP4Y7JedpEI5IPnCyWn5pVkYdBcflAYShwnN42e88uG4plBc6xQ6M4Scug8kOAFSWpHtdoXoOaC6vYtmkE3d1vw/k0WnJRMxIQiNGqjakofIhqfMTGLkvjn7KHl+FYsKkEoXar0ZbkRfiCKvRWfIoEcshl/OWxk+YNw5kIi+PlGc7PR26N1atODFebw40xRSA101g4czQM3b/NCw+x5b/ItmI37F6544GR3TZaIXEUCQGsCP52bCYWCGr7rfn9K5ax1S4dY77hdrPUmCOsRjRqo8v3GsKYD+rN56mslNGLZ35swkCcTyPM8tIwGFqy5EgWhOlIZN5EaAUjMPI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
