travis:
  secure:
    BINSTAR_TOKEN: VDx44dkOY01gS+2meRMZ0CIdLSbNkdqVvxhqGgaEap967jrkkPcovbgVv+wc5VvbJnVDzYYWaEpfKVc3Em+O9GfS0mTsPCdlGEN/+afpoAEkLrcJiCGt6AsDX74sgOpRkG+VA7qV49yEgAp+tvwY7tbZXgQNc4OCmfACGsvBJIgJ1V9Q/sM0OImb8Cz3ExVptPCAJxRG/ERUmIxtcFcZtyLwES3wJ5Xp153FTAarUnpH6M8Idg/ou28uu+J97sY+xRVNKZUVFldfXrrCwMW086CqWRSjLD8ABteHR7HNCg4XYOwaudn/+XQdWvOODLCmeLB+BimWCmbyUb7mAbo3gU1SOsvwHfhvh+dhBeVYbYzsLAehRNNXwy6+oTE2HA5bBY/6wC3CyaZdehBxwoKLkLXn5zh3Qggk9Z4nxHUZykUinhyi8yT4d+LH/1oyC/5EFpB/TDHjrH9A4IPnbQ0hbGXyWhcCo1qT6TUNokIcP+iCe+5lmtVV6KlxRfna9MxhFmvny/XA1n5d5Jwh8EMMdXB+ymgLBj8LwQ5ZMEK48JICkNlwQLWQNmYCF/ZXRtVMpCiZ+AFVMRTlaBTbwXCfWAheRkbarSfeq3rth4YU+DtgyLEGLYT7ZTXAxE8ybwo+Zgzm7etZsAD7AamyLCLzGiRRIF+B/rGtDLlXWM0L1i0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
